version: "3.9"

services:
  app:
    build:
      context: ./app
    volumes:
      - ./app:/app
    expose:
      - "8000"
    env_file:
      - ./config/environment/dev.env
    command: >
      uwsgi --emperor /app/django-uwsgi.ini
    depends_on:
      - db
  webserver:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    volumes:
        - ./config/webserver/nginx.tmpl:/etc/nginx/conf.d/nginx.tmpl
        - ./config/webserver/localhost.crt:/etc/ssl/certs/localhost.crt
        - ./config/webserver/localhost.key:/etc/ssl/private/localhost.key
    env_file:
      - ./config/environment/dev.env
    command: /bin/sh -c "envsubst < /etc/nginx/conf.d/nginx.tmpl > /etc/nginx/nginx.conf && exec nginx -g 'daemon off;'"

  db:
    image: postgres:14-alpine
    env_file:
      - ./config/environment/dev.env
